#!/usr/bin/env python3
"""Generate a minimal backend adapter skeleton from a Portkit host contract."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

CAP_MAP={
    "os.threads_messages":("threads_messages.c","portkit_threads_messages_init"),
    "os.timers_time":("timers_time.c","portkit_timers_time_init"),
    "video.vi":("video_vi.c","portkit_video_vi_init"),
    "graphics.rsp_rdp":("graphics_rsp_rdp.c","portkit_graphics_rsp_rdp_init"),
    "graphics.gbi":("graphics_gbi.c","portkit_graphics_gbi_init"),
    "audio.ai":("audio_ai.c","portkit_audio_ai_init"),
    "input.controllers":("input_controllers.c","portkit_input_controllers_init"),
    "storage.save_accessory":("storage_save_accessory.c","portkit_storage_save_accessory_init"),
    "rom.pi_cart":("rom_pi_cart.c","portkit_rom_pi_cart_init"),
    "cpu.cache_tlb":("cpu_cache_tlb.c","portkit_cpu_cache_tlb_init"),
    "cpu.arch_specific_code":("cpu_arch_specific.c","portkit_cpu_arch_specific_init"),
    "data.n64_serialization":("data_n64_serialization.c","portkit_data_n64_serialization_init"),
}

def main()->int:
    ap=argparse.ArgumentParser()
    ap.add_argument("contract",type=Path)
    ap.add_argument("--profile",type=Path,help="optional game profile with layout_contracts")
    ap.add_argument("--out",type=Path,default=Path("generated-portkit"))
    ap.add_argument("--force",action="store_true")
    args=ap.parse_args()

    contract=json.loads(args.contract.read_text())
    if contract.get("schema")!=1:
        raise SystemExit("unsupported host-contract schema")
    if not contract.get("ready_for_generation") and not args.force:
        unresolved=contract.get("unresolved",{})
        raise SystemExit(
            f"generation blocked: unresolved P0={unresolved.get('P0',0)}; "
            "classify/fix P0 hazards or pass --force for an intentionally incomplete skeleton"
        )

    args.out.mkdir(parents=True,exist_ok=True)
    manifest={"schema":1,"profile":contract.get("profile"),"generated":[],"unmapped":[],"layout_contracts":[],"offset_contracts":[],"fit_contracts":[]}

    header=["#pragma once","","/* Generated by n64-portkit. Implement only required capabilities. */",""]
    for req in contract.get("requirements",[]):
        cap=req.get("capability")
        mapped=CAP_MAP.get(cap)
        if not mapped:
            manifest["unmapped"].append(cap)
            continue
        filename,symbol=mapped
        header.append(f"int {symbol}(void);")
        body=(
            '#include "portkit_backend.h"\n\n'
            f"/* capability: {cap}\n"
            f" * source: {req.get('source_surface','unknown')}\n"
            " * TODO: bind this capability to the selected runtime/backend.\n"
            " */\n"
            f"int {symbol}(void)\n"
            "{\n"
            "    return -1;\n"
            "}\n"
        )
        (args.out/filename).write_text(body)
        manifest["generated"].append({"capability":cap,"file":filename,"symbol":symbol})

    (args.out/"portkit_backend.h").write_text("\n".join(header)+"\n")

    if args.profile:
        profile=json.loads(args.profile.read_text())
        if profile.get("schema")!=1:
            raise SystemExit("unsupported profile schema")
        contracts=profile.get("layout_contracts",[])
        if contracts:
            layout=[
                "#pragma once",
                "",
                "/* Generated by n64-portkit. Include after project type definitions. */",
                "#if defined(__cplusplus)",
                "#define PORTKIT_LAYOUT_ASSERT(cond, msg) static_assert((cond), msg)",
                "#else",
                "#define PORTKIT_LAYOUT_ASSERT(cond, msg) _Static_assert((cond), msg)",
                "#endif",
                "",
            ]
            for item in contracts:
                typename=item["type"]
                size=int(item["size"])
                why=item.get("why") or f"{typename} layout contract"
                layout.append(
                    f'PORTKIT_LAYOUT_ASSERT(sizeof({typename}) == 0x{size:x}, "{why}");'
                )
                manifest["layout_contracts"].append({
                    "type":typename,
                    "size":size,
                    "scope":item.get("scope","serialized"),
                })

            for item in profile.get("offset_contracts",[]):
                typename=item["type"]
                member=item["member"]
                offset=int(item["offset"])
                why=item.get("why") or f"{typename}.{member} offset contract"
                layout.append(
                    f'PORTKIT_LAYOUT_ASSERT(__builtin_offsetof({typename}, {member}) == 0x{offset:x}, "{why}");'
                )
                manifest["offset_contracts"].append({
                    "type":typename,
                    "member":member,
                    "offset":offset,
                })

            for item in profile.get("fit_contracts",[]):
                payload=item["payload_type"]
                container=item["container_type"]
                why=item.get("why") or f"{payload} must fit in {container}"
                layout.append(
                    f'PORTKIT_LAYOUT_ASSERT(sizeof({payload}) <= sizeof({container}), "{why}");'
                )
                manifest["fit_contracts"].append({
                    "payload_type":payload,
                    "container_type":container,
                })

            layout += ["", "#undef PORTKIT_LAYOUT_ASSERT", ""]
            (args.out/"portkit_layout_contracts.h").write_text("\n".join(layout))

    sources=[x["file"] for x in manifest["generated"]]
    cmake=[
        "cmake_minimum_required(VERSION 3.16)",
        "project(portkit_generated C)",
        "",
        "add_library(portkit_generated STATIC",
    ]
    cmake.extend(f"  {name}" for name in sources)
    cmake += [
        ")",
        "",
        "target_include_directories(portkit_generated PUBLIC",
        "  \${CMAKE_CURRENT_SOURCE_DIR}",
        ")",
        "",
        "# The parent project supplies platform/runtime libraries and compile definitions.",
        "",
    ]
    (args.out/"CMakeLists.txt").write_text("\n".join(cmake))

    manifest["build"]={"system":"cmake","file":"CMakeLists.txt","target":"portkit_generated"}
    (args.out/"manifest.json").write_text(json.dumps(manifest,indent=2)+"\n")
    print(f"generated={len(manifest['generated'])} unmapped={len(manifest['unmapped'])}")
    return 0

if __name__=="__main__":
    raise SystemExit(main())
